const characters = [
  // Swedish/Finnish/German
  { symbol: "å", name: "Latin Small Letter A with Ring Above", code: "U+00E5" },
  { symbol: "Å", name: "Latin Capital Letter A with Ring Above", code: "U+00C5" },
  { symbol: "ä", name: "Latin Small Letter A with Diaeresis", code: "U+00E4" },
  { symbol: "Ä", name: "Latin Capital Letter A with Diaeresis", code: "U+00C4" },
  { symbol: "ö", name: "Latin Small Letter O with Diaeresis", code: "U+00F6" },
  { symbol: "Ö", name: "Latin Capital Letter O with Diaeresis", code: "U+00D6" },
  { symbol: "ü", name: "Latin Small Letter U with Diaeresis", code: "U+00FC" },
  { symbol: "Ü", name: "Latin Capital Letter U with Diaeresis", code: "U+00DC" },
  // French
  { symbol: "ç", name: "French Small Letter C with Cedilla", code: "U+00E7" },
  { symbol: "Ç", name: "French Capital Letter C with Cedilla", code: "U+00C7" },
  { symbol: "é", name: "French Small Letter E with Acute", code: "U+00E9" },
  { symbol: "É", name: "French Capital Letter E with Acute", code: "U+00C9" },
  { symbol: "à", name: "French Small Letter A with Grave", code: "U+00E0" },
  { symbol: "À", name: "French Capital Letter A with Grave", code: "U+00C0" },
  { symbol: "è", name: "French Small Letter E with Grave", code: "U+00E8" },
  { symbol: "È", name: "French Capital Letter E with Grave", code: "U+00C8" },
  { symbol: "ù", name: "French Small Letter U with Grave", code: "U+00F9" },
  { symbol: "Ù", name: "French Capital Letter U with Grave", code: "U+00D9" },
  { symbol: "â", name: "French Small Letter A with Circumflex", code: "U+00E2" },
  { symbol: "Â", name: "French Capital Letter A with Circumflex", code: "U+00C2" },
  { symbol: "ê", name: "French Small Letter E with Circumflex", code: "U+00EA" },
  { symbol: "Ê", name: "French Capital Letter E with Circumflex", code: "U+00CA" },
  { symbol: "î", name: "French Small Letter I with Circumflex", code: "U+00EE" },
  { symbol: "Î", name: "French Capital Letter I with Circumflex", code: "U+00CE" },
  { symbol: "ô", name: "French Small Letter O with Circumflex", code: "U+00F4" },
  { symbol: "Ô", name: "French Capital Letter O with Circumflex", code: "U+00D4" },
  { symbol: "û", name: "French Small Letter U with Circumflex", code: "U+00FB" },
  { symbol: "Û", name: "French Capital Letter U with Circumflex", code: "U+00DB" },
  { symbol: "ï", name: "French Small Letter I with Diaeresis", code: "U+00EF" },
  { symbol: "Ï", name: "French Capital Letter I with Diaeresis", code: "U+00CF" },
  { symbol: "Œ", name: "French Capital Ligature OE", code: "U+0152" },
  // Spanish
  { symbol: "ñ", name: "Spanish Small Letter N with Tilde", code: "U+00F1" },
  { symbol: "Ñ", name: "Spanish Capital Letter N with Tilde", code: "U+00D1" },
  { symbol: "¡", name: "Spanish Inverted Exclamation Mark", code: "U+00A1" },
  { symbol: "á", name: "Spanish Small Letter A with Acute", code: "U+00E1" },
  { symbol: "Á", name: "Spanish Capital Letter A with Acute", code: "U+00C1" },
  { symbol: "í", name: "Spanish Small Letter I with Acute", code: "U+00ED" },
  { symbol: "Í", name: "Spanish Capital Letter I with Acute", code: "U+00CD" },
  { symbol: "ó", name: "Spanish Small Letter O with Acute", code: "U+00F3" },
  { symbol: "Ó", name: "Spanish Capital Letter O with Acute", code: "U+00D3" },
  { symbol: "ú", name: "Spanish Small Letter U with Acute", code: "U+00FA" },
  { symbol: "Ú", name: "Spanish Capital Letter U with Acute", code: "U+00DA" },
  { symbol: "¹", name: "Superscript One", code: "U+00B9" },
  { symbol: "²", name: "Superscript Two", code: "U+00B2" },
  { symbol: "³", name: "Superscript Three", code: "U+00B3" },
  { symbol: "¼", name: "Vulgar Fraction One Quarter", code: "U+00BC" },
  { symbol: "√", name: "Square Root", code: "U+221A" },
  { symbol: "÷", name: "Division Sign", code: "U+00F7" },
  { symbol: "«", name: "Left-Pointing Double Angle Quotation Mark", code: "U+00AB" },
  { symbol: "»", name: "Right-Pointing Double Angle Quotation Mark", code: "U+00BB" },
  { symbol: "°", name: "Degree Sign", code: "U+00B0" },
  { symbol: "¿", name: "Inverted Question Mark", code: "U+00BF" },
  { symbol: "ë", name: "Latin Small Letter E with Diaeresis", code: "U+00EB" },
  { symbol: "¨", name: "Diaeresis", code: "U+00A8" },
  { symbol: "©", name: "Copyright Sign", code: "U+00A9" },
  { symbol: "ã", name: "Latin Small Letter A with Tilde", code: "U+00E3" },
  { symbol: "ῶ", name: "Greek Small Letter Omega with Perispomeni", code: "U+1FF6" },
  { symbol: "~", name: "Tilde", code: "U+007E" },
  { symbol: "σ", name: "Greek Small Letter Sigma", code: "U+03C3" },
  { symbol: "€", name: "Euro Sign", code: "U+20AC" },
  { symbol: "®", name: "Registered Sign", code: "U+00AE" },
  { symbol: "þ", name: "Latin Small Letter Thorn", code: "U+00FE" },
  { symbol: "←", name: "Leftwards Arrow", code: "U+2190" },
  { symbol: "→", name: "Rightwards Arrow", code: "U+2192" },
  { symbol: "œ", name: "Latin Small Ligature OE", code: "U+0153" },
  { symbol: "π", name: "Greek Small Letter Pi", code: "U+03C0" },
  { symbol: "æ", name: "Latin Small Letter AE", code: "U+00E6" },
  { symbol: "ø", name: "Latin Small Letter O with Stroke", code: "U+00F8" },
  { symbol: "ł", name: "Latin Small Letter L with Stroke", code: "U+0142" },
  { symbol: "ĸ", name: "Latin Small Letter Kra", code: "U+0138" },
  { symbol: "ħ", name: "Latin Small Letter H with Stroke", code: "U+0127" },
  { symbol: "ŋ", name: "Latin Small Letter Eng", code: "U+014B" },
  { symbol: "đ", name: "Latin Small Letter D with Stroke", code: "U+0111" },
  { symbol: "ð", name: "Latin Small Letter Eth", code: "U+00F0" },
  { symbol: "ß", name: "Latin Small Letter Sharp S", code: "U+00DF" },
  { symbol: "ª", name: "Feminine Ordinal Indicator", code: "U+00AA" },
  { symbol: "„", name: "Double Low-9 Quotation Mark", code: "U+201E" },
  { symbol: "“", name: "Left Double Quotation Mark", code: "U+201C" },
  { symbol: "”", name: "Right Double Quotation Mark", code: "U+201D" },
  { symbol: "µ", name: "Micro Sign", code: "U+00B5" },
  { symbol: "·", name: "Middle Dot", code: "U+00B7" },
  { symbol: "–", name: "En Dash", code: "U+2013" },
  { symbol: "—", name: "Em Dash", code: "U+2014" },
  { symbol: "†", name: "Dagger", code: "U+2020" },
  { symbol: "‡", name: "Double Dagger", code: "U+2021" },
  { symbol: "•", name: "Bullet", code: "U+2022" },
  { symbol: "…", name: "Horizontal Ellipsis", code: "U+2026" },
  { symbol: "‰", name: "Per Mille Sign", code: "U+2030" },
  { symbol: "′", name: "Prime", code: "U+2032" },
  { symbol: "″", name: "Double Prime", code: "U+2033" },
  { symbol: "‹", name: "Single Left-Pointing Angle Quotation Mark", code: "U+2039" },
  { symbol: "›", name: "Single Right-Pointing Angle Quotation Mark", code: "U+203A" },
  { symbol: "‾", name: "Overline", code: "U+203E" },
  { symbol: "⁄", name: "Fraction Slash", code: "U+2044" },
  { symbol: "™", name: "Trade Mark Sign", code: "U+2122" },
  { symbol: "ℵ", name: "Alef Symbol", code: "U+2135" },
  { symbol: "↑", name: "Upwards Arrow", code: "U+2191" },
  { symbol: "↓", name: "Downwards Arrow", code: "U+2193" },
  { symbol: "↔", name: "Left Right Arrow", code: "U+2194" },
  { symbol: "↵", name: "Downwards Arrow with Corner Leftwards", code: "U+21B5" },
  { symbol: "⇐", name: "Leftwards Double Arrow", code: "U+21D0" },
  { symbol: "⇒", name: "Rightwards Double Arrow", code: "U+21D2" },
  { symbol: "⇔", name: "Left Right Double Arrow", code: "U+21D4" },
  { symbol: "∀", name: "For All", code: "U+2200" },
  { symbol: "∂", name: "Partial Differential", code: "U+2202" },
  { symbol: "∃", name: "There Exists", code: "U+2203" },
  { symbol: "∅", name: "Empty Set", code: "U+2205" },
  { symbol: "∇", name: "Nabla", code: "U+2207" },
  { symbol: "∈", name: "Element Of", code: "U+2208" },
  { symbol: "∉", name: "Not an Element Of", code: "U+2209" },
  { symbol: "∋", name: "Contains as Member", code: "U+220B" },
  { symbol: "∏", name: "N-Ary Product", code: "U+220F" },
  { symbol: "∑", name: "N-Ary Summation", code: "U+2211" },
  { symbol: "−", name: "Minus Sign", code: "U+2212" },
  { symbol: "∗", name: "Asterisk Operator", code: "U+2217" },
  { symbol: "∝", name: "Proportional To", code: "U+221D" },
  { symbol: "∞", name: "Infinity", code: "U+221E" },
  { symbol: "∠", name: "Angle", code: "U+2220" },
  { symbol: "∧", name: "Logical And", code: "U+2227" },
  { symbol: "∨", name: "Logical Or", code: "U+2228" },
  { symbol: "∩", name: "Intersection", code: "U+2229" },
  { symbol: "∪", name: "Union", code: "U+222A" },
  { symbol: "∫", name: "Integral", code: "U+222B" },
  { symbol: "∴", name: "Therefore", code: "U+2234" },
  { symbol: "∼", name: "Tilde Operator", code: "U+223C" },
  { symbol: "≅", name: "Approximately Equal To", code: "U+2245" },
  { symbol: "≈", name: "Almost Equal To", code: "U+2248" },
  { symbol: "≠", name: "Not Equal To", code: "U+2260" },
  { symbol: "≡", name: "Identical To", code: "U+2261" },
  { symbol: "≤", name: "Less-Than or Equal To", code: "U+2264" },
  { symbol: "≥", name: "Greater-Than or Equal To", code: "U+2265" },
  { symbol: "⊂", name: "Subset Of", code: "U+2282" },
  { symbol: "⊃", name: "Superset Of", code: "U+2283" },
  { symbol: "⊄", name: "Not a Subset Of", code: "U+2284" },
  { symbol: "⊆", name: "Subset Of Or Equal To", code: "U+2286" },
  { symbol: "⊇", name: "Superset Of Or Equal To", code: "U+2287" },
  { symbol: "⊕", name: "Circled Plus", code: "U+2295" },
  { symbol: "⊗", name: "Circled Times", code: "U+2297" },
  { symbol: "⊥", name: "Up Tack", code: "U+22A5" },
  { symbol: "⋅", name: "Dot Operator", code: "U+22C5" },
  { symbol: "⌈", name: "Left Ceiling", code: "U+2308" },
  { symbol: "⌉", name: "Right Ceiling", code: "U+2309" },
  { symbol: "⌊", name: "Left Floor", code: "U+230A" },
  { symbol: "⌋", name: "Right Floor", code: "U+230B" },
  { symbol: "⟨", name: "Left-Pointing Angle Bracket", code: "U+2329" },
  { symbol: "⟩", name: "Right-Pointing Angle Bracket", code: "U+232A" },
  { symbol: "✓", name: "Check Mark", code: "U+2713" },
  { symbol: "✗", name: "Ballot X", code: "U+2717" },
  { symbol: "★", name: "Black Star", code: "U+2605" },
  { symbol: "☆", name: "White Star", code: "U+2606" },
  { symbol: "♀", name: "Female Sign", code: "U+2640" },
  { symbol: "♂", name: "Male Sign", code: "U+2642" },
  { symbol: "♠", name: "Black Spade Suit", code: "U+2660" },
  { symbol: "♣", name: "Black Club Suit", code: "U+2663" },
  { symbol: "♥", name: "Black Heart Suit", code: "U+2665" },
  { symbol: "♦", name: "Black Diamond Suit", code: "U+2666" },
];
