const characterCategories = {
  accented: {
    name: "Accented Letters",
    description: "Letters with diacritical marks for various languages",
    characters: [
      { symbol: "À", name: "French Capital Letter A with Grave", code: "U+00C0", aliases: ["A", "a", "french"], category: "accented" },
      { symbol: "Á", name: "Spanish Capital Letter A with Acute", code: "U+00C1", aliases: ["A", "a", "spanish"], category: "accented" },
      { symbol: "Â", name: "French Capital Letter A with Circumflex", code: "U+00C2", aliases: ["A", "a", "french"], category: "accented" },
      { symbol: "Ã", name: "Portuguese Capital Letter A with Tilde", code: "U+00C3", aliases: ["A", "a", "portuguese"], category: "accented" },
      { symbol: "Ä", name: "German Capital Letter A with Diaeresis", code: "U+00C4", aliases: ["A", "a", "german"], category: "accented" },
      { symbol: "Å", name: "Nordic Capital Letter A with Ring Above", code: "U+00C5", aliases: ["A", "a", "nordic", "swedish", "norwegian"], category: "accented" },
      { symbol: "Æ", name: "Nordic Capital Letter AE", code: "U+00C6", aliases: ["AE", "ae", "nordic"], category: "accented" },
      { symbol: "Ç", name: "French Capital Letter C with Cedilla", code: "U+00C7", aliases: ["C", "c", "french"], category: "accented" },
      { symbol: "È", name: "French Capital Letter E with Grave", code: "U+00C8", aliases: ["E", "e", "french"], category: "accented" },
      { symbol: "É", name: "French Capital Letter E with Acute", code: "U+00C9", aliases: ["E", "e", "french"], category: "accented" },
      { symbol: "Ê", name: "French Capital Letter E with Circumflex", code: "U+00CA", aliases: ["E", "e", "french"], category: "accented" },
      { symbol: "Ë", name: "German Capital Letter E with Diaeresis", code: "U+00CB", aliases: ["E", "e", "german"], category: "accented" },
      { symbol: "Ì", name: "Italian Capital Letter I with Grave", code: "U+00CC", aliases: ["I", "i", "italian"], category: "accented" },
      { symbol: "Í", name: "Spanish Capital Letter I with Acute", code: "U+00CD", aliases: ["I", "i", "spanish"], category: "accented" },
      { symbol: "Î", name: "French Capital Letter I with Circumflex", code: "U+00CE", aliases: ["I", "i", "french"], category: "accented" },
      { symbol: "Ï", name: "German Capital Letter I with Diaeresis", code: "U+00CF", aliases: ["I", "i", "german"], category: "accented" },
      { symbol: "Ð", name: "Icelandic Capital Letter Eth", code: "U+00D0", aliases: ["D", "d", "icelandic"], category: "accented" },
      { symbol: "Ñ", name: "Spanish Capital Letter N with Tilde", code: "U+00D1", aliases: ["N", "n", "spanish"], category: "accented" },
      { symbol: "Ò", name: "Italian Capital Letter O with Grave", code: "U+00D2", aliases: ["O", "o", "italian"], category: "accented" },
      { symbol: "Ó", name: "Spanish Capital Letter O with Acute", code: "U+00D3", aliases: ["O", "o", "spanish"], category: "accented" },
      { symbol: "Ô", name: "French Capital Letter O with Circumflex", code: "U+00D4", aliases: ["O", "o", "french"], category: "accented" },
      { symbol: "Õ", name: "Portuguese Capital Letter O with Tilde", code: "U+00D5", aliases: ["O", "o", "portuguese"], category: "accented" },
      { symbol: "Ö", name: "German Capital Letter O with Diaeresis", code: "U+00D6", aliases: ["O", "o", "german"], category: "accented" },
      { symbol: "Ø", name: "Nordic Capital Letter O with Stroke", code: "U+00D8", aliases: ["O", "o", "nordic"], category: "accented" },
      { symbol: "Ù", name: "Italian Capital Letter U with Grave", code: "U+00D9", aliases: ["U", "u", "italian"], category: "accented" },
      { symbol: "Ú", name: "Spanish Capital Letter U with Acute", code: "U+00DA", aliases: ["U", "u", "spanish"], category: "accented" },
      { symbol: "Û", name: "French Capital Letter U with Circumflex", code: "U+00DB", aliases: ["U", "u", "french"], category: "accented" },
      { symbol: "Ü", name: "German Capital Letter U with Diaeresis", code: "U+00DC", aliases: ["U", "u", "german"], category: "accented" },
      { symbol: "Ý", name: "Spanish Capital Letter Y with Acute", code: "U+00DD", aliases: ["Y", "y", "spanish"], category: "accented" },
      { symbol: "Þ", name: "Icelandic Capital Letter Thorn", code: "U+00DE", aliases: ["TH", "th", "icelandic"], category: "accented" },
      { symbol: "ß", name: "German Small Letter Sharp S", code: "U+00DF", aliases: ["ss", "german"], category: "accented" },
      { symbol: "à", name: "French Small Letter A with Grave", code: "U+00E0", aliases: ["a", "french"], category: "accented" },
      { symbol: "á", name: "Spanish Small Letter A with Acute", code: "U+00E1", aliases: ["a", "spanish"], category: "accented" },
      { symbol: "â", name: "French Small Letter A with Circumflex", code: "U+00E2", aliases: ["a", "french"], category: "accented" },
      { symbol: "ã", name: "Portuguese Small Letter A with Tilde", code: "U+00E3", aliases: ["a", "portuguese"], category: "accented" },
      { symbol: "ä", name: "German Small Letter A with Diaeresis", code: "U+00E4", aliases: ["a", "german"], category: "accented" },
      { symbol: "å", name: "Nordic Small Letter A with Ring Above", code: "U+00E5", aliases: ["a", "nordic"], category: "accented" },
      { symbol: "æ", name: "Nordic Small Letter AE", code: "U+00E6", aliases: ["ae", "nordic"], category: "accented" },
      { symbol: "ç", name: "French Small Letter C with Cedilla", code: "U+00E7", aliases: ["c", "french"], category: "accented" },
      { symbol: "è", name: "French Small Letter E with Grave", code: "U+00E8", aliases: ["e", "french"], category: "accented" },
      { symbol: "é", name: "French Small Letter E with Acute", code: "U+00E9", aliases: ["e", "french"], category: "accented" },
      { symbol: "ê", name: "French Small Letter E with Circumflex", code: "U+00EA", aliases: ["e", "french"], category: "accented" },
      { symbol: "ë", name: "German Small Letter E with Diaeresis", code: "U+00EB", aliases: ["e", "german"], category: "accented" },
      { symbol: "ì", name: "Italian Small Letter I with Grave", code: "U+00EC", aliases: ["i", "italian"], category: "accented" },
      { symbol: "í", name: "Spanish Small Letter I with Acute", code: "U+00ED", aliases: ["i", "spanish"], category: "accented" },
      { symbol: "î", name: "French Small Letter I with Circumflex", code: "U+00EE", aliases: ["i", "french"], category: "accented" },
      { symbol: "ï", name: "German Small Letter I with Diaeresis", code: "U+00EF", aliases: ["i", "german"], category: "accented" },
      { symbol: "ð", name: "Icelandic Small Letter Eth", code: "U+00F0", aliases: ["d", "icelandic"], category: "accented" },
      { symbol: "ñ", name: "Spanish Small Letter N with Tilde", code: "U+00F1", aliases: ["n", "spanish"], category: "accented" },
      { symbol: "ò", name: "Italian Small Letter O with Grave", code: "U+00F2", aliases: ["o", "italian"], category: "accented" },
      { symbol: "ó", name: "Spanish Small Letter O with Acute", code: "U+00F3", aliases: ["o", "spanish"], category: "accented" },
      { symbol: "ô", name: "French Small Letter O with Circumflex", code: "U+00F4", aliases: ["o", "french"], category: "accented" },
      { symbol: "õ", name: "Portuguese Small Letter O with Tilde", code: "U+00F5", aliases: ["o", "portuguese"], category: "accented" },
      { symbol: "ö", name: "German Small Letter O with Diaeresis", code: "U+00F6", aliases: ["o", "german"], category: "accented" },
      { symbol: "ø", name: "Nordic Small Letter O with Stroke", code: "U+00F8", aliases: ["o", "nordic"], category: "accented" },
      { symbol: "ù", name: "Italian Small Letter U with Grave", code: "U+00F9", aliases: ["u", "italian"], category: "accented" },
      { symbol: "ú", name: "Spanish Small Letter U with Acute", code: "U+00FA", aliases: ["u", "spanish"], category: "accented" },
      { symbol: "û", name: "French Small Letter U with Circumflex", code: "U+00FB", aliases: ["u", "french"], category: "accented" },
      { symbol: "ü", name: "German Small Letter U with Diaeresis", code: "U+00FC", aliases: ["u", "german"], category: "accented" },
      { symbol: "ý", name: "Spanish Small Letter Y with Acute", code: "U+00FD", aliases: ["y", "spanish"], category: "accented" },
      { symbol: "þ", name: "Icelandic Small Letter Thorn", code: "U+00FE", aliases: ["th", "icelandic"], category: "accented" },
      { symbol: "ÿ", name: "French Small Letter Y with Diaeresis", code: "U+00FF", aliases: ["y", "french"], category: "accented" },
    ]
  },
  
  math: {
    name: "Mathematical Symbols & Numbers",
    description: "Mathematical operators, symbols, and numeric characters including fractions",
    characters: [
      { symbol: "±", name: "Plus-Minus Sign", code: "U+00B1", aliases: ["plus", "minus", "pm"], category: "math" },
      { symbol: "×", name: "Multiplication Sign", code: "U+00D7", aliases: ["multiply", "times", "x"], category: "math" },
      { symbol: "÷", name: "Division Sign", code: "U+00F7", aliases: ["divide", "division"], category: "math" },
      { symbol: "≠", name: "Not Equal To", code: "U+2260", aliases: ["not", "equal", "ne"], category: "math" },
      { symbol: "≤", name: "Less Than or Equal To", code: "U+2264", aliases: ["less", "equal", "le"], category: "math" },
      { symbol: "≥", name: "Greater Than or Equal To", code: "U+2265", aliases: ["greater", "equal", "ge"], category: "math" },
      { symbol: "∞", name: "Infinity", code: "U+221E", aliases: ["infinity", "inf"], category: "math" },
      { symbol: "∑", name: "N-Ary Summation", code: "U+2211", aliases: ["sum", "sigma"], category: "math" },
      { symbol: "∏", name: "N-Ary Product", code: "U+220F", aliases: ["product", "pi"], category: "math" },
      { symbol: "∫", name: "Integral", code: "U+222B", aliases: ["integral", "int"], category: "math" },
      { symbol: "∂", name: "Partial Differential", code: "U+2202", aliases: ["partial", "derivative"], category: "math" },
      { symbol: "∆", name: "Increment", code: "U+2206", aliases: ["delta", "change"], category: "math" },
      { symbol: "√", name: "Square Root", code: "U+221A", aliases: ["sqrt", "root"], category: "math" },
      { symbol: "∝", name: "Proportional To", code: "U+221D", aliases: ["proportional", "prop"], category: "math" },
      { symbol: "∈", name: "Element Of", code: "U+2208", aliases: ["element", "in"], category: "math" },
      { symbol: "∉", name: "Not an Element Of", code: "U+2209", aliases: ["not", "element"], category: "math" },
      { symbol: "∅", name: "Empty Set", code: "U+2205", aliases: ["empty", "null", "set"], category: "math" },
      { symbol: "∩", name: "Intersection", code: "U+2229", aliases: ["intersection", "and"], category: "math" },
      { symbol: "∪", name: "Union", code: "U+222A", aliases: ["union", "or"], category: "math" },
      { symbol: "⊂", name: "Subset Of", code: "U+2282", aliases: ["subset"], category: "math" },
      { symbol: "⊃", name: "Superset Of", code: "U+2283", aliases: ["superset"], category: "math" },
      { symbol: "⊆", name: "Subset Of or Equal To", code: "U+2286", aliases: ["subset", "equal"], category: "math" },
      { symbol: "⊇", name: "Superset Of or Equal To", code: "U+2287", aliases: ["superset", "equal"], category: "math" },
      { symbol: "∀", name: "For All", code: "U+2200", aliases: ["forall", "all"], category: "math" },
      { symbol: "∃", name: "There Exists", code: "U+2203", aliases: ["exists", "some"], category: "math" },
      { symbol: "∄", name: "There Does Not Exist", code: "U+2204", aliases: ["not", "exists"], category: "math" },
      { symbol: "∧", name: "Logical And", code: "U+2227", aliases: ["and", "logical"], category: "math" },
      { symbol: "∨", name: "Logical Or", code: "U+2228", aliases: ["or", "logical"], category: "math" },
      { symbol: "¬", name: "Not Sign", code: "U+00AC", aliases: ["not", "logical"], category: "math" },
      { symbol: "⊕", name: "Circled Plus", code: "U+2295", aliases: ["xor", "plus"], category: "math" },
      { symbol: "⊗", name: "Circled Times", code: "U+2297", aliases: ["times", "tensor"], category: "math" },
      { symbol: "°", name: "Degree Sign", code: "U+00B0", aliases: ["degree", "temp"], category: "math" },
      { symbol: "′", name: "Prime", code: "U+2032", aliases: ["prime", "minute"], category: "math" },
      { symbol: "″", name: "Double Prime", code: "U+2033", aliases: ["double", "prime", "second"], category: "math" },
      { symbol: "‰", name: "Per Mille Sign", code: "U+2030", aliases: ["permille", "thousand"], category: "math" },
      { symbol: "‱", name: "Per Ten Thousand Sign", code: "U+2031", aliases: ["basis", "point"], category: "math" },
      // Fractions and superscripts (moved from fractions category)
      { symbol: "½", name: "Vulgar Fraction One Half", code: "U+00BD", aliases: ["1/2", "half"], category: "math" },
      { symbol: "⅓", name: "Vulgar Fraction One Third", code: "U+2153", aliases: ["1/3", "third"], category: "math" },
      { symbol: "⅔", name: "Vulgar Fraction Two Thirds", code: "U+2154", aliases: ["2/3", "thirds"], category: "math" },
      { symbol: "¼", name: "Vulgar Fraction One Quarter", code: "U+00BC", aliases: ["1/4", "quarter"], category: "math" },
      { symbol: "¾", name: "Vulgar Fraction Three Quarters", code: "U+00BE", aliases: ["3/4", "quarters"], category: "math" },
      { symbol: "⅕", name: "Vulgar Fraction One Fifth", code: "U+2155", aliases: ["1/5", "fifth"], category: "math" },
      { symbol: "⅖", name: "Vulgar Fraction Two Fifths", code: "U+2156", aliases: ["2/5", "fifths"], category: "math" },
      { symbol: "⅗", name: "Vulgar Fraction Three Fifths", code: "U+2157", aliases: ["3/5", "fifths"], category: "math" },
      { symbol: "⅘", name: "Vulgar Fraction Four Fifths", code: "U+2158", aliases: ["4/5", "fifths"], category: "math" },
      { symbol: "⅙", name: "Vulgar Fraction One Sixth", code: "U+2159", aliases: ["1/6", "sixth"], category: "math" },
      { symbol: "⅚", name: "Vulgar Fraction Five Sixths", code: "U+215A", aliases: ["5/6", "sixths"], category: "math" },
      { symbol: "⅛", name: "Vulgar Fraction One Eighth", code: "U+215B", aliases: ["1/8", "eighth"], category: "math" },
      { symbol: "⅜", name: "Vulgar Fraction Three Eighths", code: "U+215C", aliases: ["3/8", "eighths"], category: "math" },
      { symbol: "⅝", name: "Vulgar Fraction Five Eighths", code: "U+215D", aliases: ["5/8", "eighths"], category: "math" },
      { symbol: "⅞", name: "Vulgar Fraction Seven Eighths", code: "U+215E", aliases: ["7/8", "eighths"], category: "math" },
      { symbol: "¹", name: "Superscript One", code: "U+00B9", aliases: ["1", "super1"], category: "math" },
      { symbol: "²", name: "Superscript Two", code: "U+00B2", aliases: ["2", "super2", "squared"], category: "math" },
      { symbol: "³", name: "Superscript Three", code: "U+00B3", aliases: ["3", "super3", "cubed"], category: "math" },
      { symbol: "⁴", name: "Superscript Four", code: "U+2074", aliases: ["4", "super4"], category: "math" },
      { symbol: "⁵", name: "Superscript Five", code: "U+2075", aliases: ["5", "super5"], category: "math" },
      { symbol: "⁶", name: "Superscript Six", code: "U+2076", aliases: ["6", "super6"], category: "math" },
      { symbol: "⁷", name: "Superscript Seven", code: "U+2077", aliases: ["7", "super7"], category: "math" },
      { symbol: "⁸", name: "Superscript Eight", code: "U+2078", aliases: ["8", "super8"], category: "math" },
      { symbol: "⁹", name: "Superscript Nine", code: "U+2079", aliases: ["9", "super9"], category: "math" },
      { symbol: "⁰", name: "Superscript Zero", code: "U+2070", aliases: ["0", "super0"], category: "math" },
    ]
  },
  
  punctuation: {
    name: "Punctuation & Typography",
    description: "Special punctuation marks and typography symbols",
    characters: [
      { symbol: "«", name: "Left-Pointing Double Angle Quotation Mark", code: "U+00AB", aliases: ["quote", "<<"], category: "punctuation" },
      { symbol: "»", name: "Right-Pointing Double Angle Quotation Mark", code: "U+00BB", aliases: ["quote", ">>"], category: "punctuation" },
      { symbol: "‹", name: "Single Left-Pointing Angle Quotation Mark", code: "U+2039", aliases: ["quote", "<"], category: "punctuation" },
      { symbol: "›", name: "Single Right-Pointing Angle Quotation Mark", code: "U+203A", aliases: ["quote", ">"], category: "punctuation" },
      { symbol: "„", name: "Double Low-9 Quotation Mark", code: "U+201E", aliases: ["quote"], category: "punctuation" },
      { symbol: "\u201C", name: "Left Double Quotation Mark", code: "U+201C", aliases: ["quote"], category: "punctuation" },
      { symbol: "\u201D", name: "Right Double Quotation Mark", code: "U+201D", aliases: ["quote"], category: "punctuation" },
      { symbol: "'", name: "Left Single Quotation Mark", code: "U+2018", aliases: ["quote", "'"], category: "punctuation" },
      { symbol: "'", name: "Right Single Quotation Mark", code: "U+2019", aliases: ["quote", "'"], category: "punctuation" },
      { symbol: "–", name: "En Dash", code: "U+2013", aliases: ["dash", "-"], category: "punctuation" },
      { symbol: "—", name: "Em Dash", code: "U+2014", aliases: ["dash", "--"], category: "punctuation" },
      { symbol: "…", name: "Horizontal Ellipsis", code: "U+2026", aliases: ["ellipsis", "..."], category: "punctuation" },
      { symbol: "•", name: "Bullet", code: "U+2022", aliases: ["bullet", "dot"], category: "punctuation" },
      { symbol: "†", name: "Dagger", code: "U+2020", aliases: ["dagger"], category: "punctuation" },
      { symbol: "‡", name: "Double Dagger", code: "U+2021", aliases: ["double-dagger"], category: "punctuation" },
      { symbol: "‾", name: "Overline", code: "U+203E", aliases: ["overline"], category: "punctuation" },
      { symbol: "⁄", name: "Fraction Slash", code: "U+2044", aliases: ["fraction", "/"], category: "punctuation" },
      { symbol: "′", name: "Prime", code: "U+2032", aliases: ["prime", "'"], category: "punctuation" },
      { symbol: "″", name: "Double Prime", code: "U+2033", aliases: ["double-prime", "''"], category: "punctuation" },
    ]
  },
  
  symbols: {
    name: "General Symbols",
    description: "Currency, copyright, and other common symbols",
    characters: [
      { symbol: "€", name: "Euro Sign", code: "U+20AC", aliases: ["euro", "eur"], category: "symbols" },
      { symbol: "£", name: "Pound Sign", code: "U+00A3", aliases: ["pound", "gbp"], category: "symbols" },
      { symbol: "¥", name: "Yen Sign", code: "U+00A5", aliases: ["yen", "jpy"], category: "symbols" },
      { symbol: "$", name: "Dollar Sign", code: "U+0024", aliases: ["dollar", "usd"], category: "symbols" },
      { symbol: "¢", name: "Cent Sign", code: "U+00A2", aliases: ["cent"], category: "symbols" },
      { symbol: "©", name: "Copyright Sign", code: "U+00A9", aliases: ["copyright", "(c)"], category: "symbols" },
      { symbol: "®", name: "Registered Sign", code: "U+00AE", aliases: ["registered", "(r)"], category: "symbols" },
      { symbol: "™", name: "Trade Mark Sign", code: "U+2122", aliases: ["trademark", "tm"], category: "symbols" },
      { symbol: "°", name: "Degree Sign", code: "U+00B0", aliases: ["degree", "deg"], category: "symbols" },
      { symbol: "µ", name: "Micro Sign", code: "U+00B5", aliases: ["micro", "mu"], category: "symbols" },
      { symbol: "‰", name: "Per Mille Sign", code: "U+2030", aliases: ["permille", "per-mille"], category: "symbols" },
      { symbol: "§", name: "Section Sign", code: "U+00A7", aliases: ["section"], category: "symbols" },
      { symbol: "¶", name: "Pilcrow Sign", code: "U+00B6", aliases: ["paragraph", "pilcrow"], category: "symbols" },
      { symbol: "←", name: "Leftwards Arrow", code: "U+2190", aliases: ["arrow", "left"], category: "symbols" },
      { symbol: "→", name: "Rightwards Arrow", code: "U+2192", aliases: ["arrow", "right"], category: "symbols" },
      { symbol: "↑", name: "Upwards Arrow", code: "U+2191", aliases: ["arrow", "up"], category: "symbols" },
      { symbol: "↓", name: "Downwards Arrow", code: "U+2193", aliases: ["arrow", "down"], category: "symbols" },
      { symbol: "¿", name: "Inverted Question Mark", code: "U+00BF", aliases: ["question", "?"], category: "symbols" },
      { symbol: "¡", name: "Spanish Inverted Exclamation Mark", code: "U+00A1", aliases: ["exclamation", "!"], category: "symbols" },
      { symbol: "·", name: "Middle Dot", code: "U+00B7", aliases: ["dot", "middle-dot"], category: "symbols" },
      { symbol: "¨", name: "Diaeresis", code: "U+00A8", aliases: ["diaeresis", "umlaut"], category: "symbols" },
      { symbol: "~", name: "Tilde", code: "U+007E", aliases: ["tilde"], category: "symbols" },
      { symbol: "ª", name: "Feminine Ordinal Indicator", code: "U+00AA", aliases: ["ordinal", "a"], category: "symbols" },
      { symbol: "º", name: "Masculine Ordinal Indicator", code: "U+00BA", aliases: ["ordinal", "o"], category: "symbols" },
    ]
  },
};

// Flatten all characters into a single array for backward compatibility
const characters = Object.values(characterCategories).flatMap(category => 
  category.characters.map(char => ({
    ...char,
    category: Object.keys(characterCategories).find(key => characterCategories[key] === category)
  }))
);
